### ISSUE TITLE
Can't seem to get tests working?

### ISSUE THREAD

**Issue by briancorbin** [tmthecoder/dargon2#20]
Whenever I run tests that use dargon2_flutter, they fail with the following

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following UnimplementedError was thrown running a test:
UnimplementedError

When the exception was thrown, this was the stack:
#0      EmptyDArgon2Flutter.hashPasswordBytes (package:dargon2_flutter_platform_interface/empty_dargon2_flutter.dart:21:5)
#1      getRandomKey (package:pointycastle_playground/main.dart:41:39)
#2      _MyHomePageState._incrementCounter (package:pointycastle_playground/main.dart:59:5)
#3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:469:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:445:22)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:331:11)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:400:7)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:363:5)
#14     TestWidgetsFlutterBinding.handlePointerEventForSource.<anonymous closure> (package:flutter_test/src/binding.dart:625:42)
#15     TestWidgetsFlutterBinding.withPointerEventSource (package:flutter_test/src/binding.dart:635:11)
#16     TestWidgetsFlutterBinding.handlePointerEventForSource (package:flutter_test/src/binding.dart:625:5)
#17     WidgetTester.sendEventToBinding.<anonymous closure> (package:flutter_test/src/widget_tester.dart:849:15)
#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#21     WidgetTester.sendEventToBinding (package:flutter_test/src/widget_tester.dart:848:27)
#22     TestGesture.up.<anonymous closure> (package:flutter_test/src/test_pointer.dart:550:26)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
#26     TestGesture.up (package:flutter_test/src/test_pointer.dart:543:27)
#27     WidgetController.tapAt.<anonymous closure> (package:flutter_test/src/controller.dart:561:21)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
```

Am I missing something that I should be doing to set this up for testing?

**Comment by tmthecoder** [comment]
Unit testing in Flutter isn't supported as FFI needs the device environment to run the native functions while Unit Test environments are run on-desktop. I am looking into testing specific initializations, but am not sure when or if this will be possible. As a temporary workaround I'd recommend using integration tests which will spin up the entire device environment.

**Comment by briancorbin** [comment]
oh, okay that's good to know, thank you!

**Comment by briancorbin** [comment]
Would you be able to share with me the difference (generally speaking) between this library and, say, [argon2](https://github.com/gmpassos/argon2) and [pointycastle](https://github.com/bcgit/pc-dart)?

**Comment by tmthecoder** [comment]
@briancorbin From what I can tell both the other two you linked above are pure Dart implementations meaning they have re-wrote the Argon2 algorithm in Dart. I utilize the C reference implementation and utilize Dart's inbuilt FFI and interact with that C reference implementation. I can't speak for performance as I haven't performed benchmarks, but I have found Pure Dart Cryptography to be slower in the case of larger cryptographic operations in the scope of AES and similar usage, so I tend to prefer going with native-based implementations

**Comment by briancorbin** [comment]
aaah I see, okay thank you for the explanation! Feel free to close this, very much appreciated :)
