### ISSUE TITLE
Failed to load dynamic library 'libargon2-arm.so': dlopen failed: library "libargon2-arm.so" not found

### ISSUE THREAD

**Issue by cliffordsugijanto** [tmthecoder/dargon2#26]
`E/flutter ( 7578): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libargon2-arm.so': dlopen failed: library "libargon2-arm.so" not found
E/flutter ( 7578): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter ( 7578): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 7578): #2      FlutterLibLoader.loadLib (package:dargon2_flutter_mobile/src/native/flutter_lib_loader.dart:26:27)
E/flutter ( 7578): #3      new LocalBinder._ (package:dargon2_core/src/native/local_binder.dart:155:31)
E/flutter ( 7578): #4      LocalBinder.initialize (package:dargon2_core/src/native/local_binder.dart:130:38)
E/flutter ( 7578): #5      new DArgon2Native (package:dargon2_core/src/native/dargon2_native.dart:17:17)
E/flutter ( 7578): #6      new DArgon2Mobile (package:dargon2_flutter_mobile/src/argon2.dart:18:20)
E/flutter ( 7578): #7      initialize (package:dargon2_flutter/src/initializer_mobile.dart:13:34)
E/flutter ( 7578): #8      DArgon2Flutter.init (package:dargon2_flutter/src/initializer.dart:9:25)
E/flutter ( 7578): #9      main (package:ucollect_app/main.dart:60:18)
E/flutter ( 7578): <asynchronous suspension>
E/flutter ( 7578): `

Environment:
`Flutter 3.24.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cf269e36d (6 days ago) • 2024-09-03 14:30:00 -0700
Engine • revision a6bd3f1de1
Tools • Dart 3.5.2 • DevTools 2.37.2
`

This error happens when i build to android, what should i do?

**Comment by SunilKividor** [comment]
did u find any solution for this ?

**Comment by SkylL3r** [comment]
Any update here ? I have the same issue after upgrading Flutter from 3.27 to 3.29 => After analyzing the output APK of my app, `libargon2-arm.so` isn't generated at all (android build/run is ok though, but exception is thrown when calling to any dargon2 method)

**Comment by Eremmmm** [comment]
> Any update here ? I have the same issue after upgrading Flutter from 3.27 to 3.29 => After analyzing the output APK of my app, `libargon2-arm.so` isn't generated at all (android build/run is ok though, but exception is thrown when calling to any dargon2 method)

I had the same problem and for lack of solution I decided to use another package that does the same things.
